//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteItem
    {
        public int ID { get; set; }
        public int Vote_ID { get; set; }
        public string Title { get; set; }
        public int Total { get; set; }
    
        public virtual Vote Vote { get; set; }
    }
}
